version: 2
updates:
  - package-ecosystem: bun
    directory: "/"
    schedule:
      interval: weekly
      time: "04:00"
    groups:
      all-deps:
        patterns: ["*"]

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: weekly
      time: "04:00"
    groups:
      all-actions:
        patterns: ["*"]
